name: LinaCore
main: nouma\Cristelia\Main
version: 1.0.0
api: 5.0.0
authors:
  - nouma
  - HacheBg

loadbefore: CustomCraft
depend: Customies

commands:
  jobs:
    description: Jobs command
    permission: cristelia

permissions:
  cristelia:
    description: "Allows the user to run the Cristelia command"
    # Default state of the permission. Explanation of each value:
    # op: only op players have this permission by default
    # true: everyone has this permission by default
    # false: no one has this permission by default
    default: true