name: Cristelia
main: nouma\cristelia\Main

version: 1.0.0
api: 5.0.0

authors:
  - Nouma
  - HacheBg

depend: [Customies, CustomScore, PiggyFactions]

commands:
  jobs:
    description: Jobs command
    permission: cristelia

permissions:
  cristelia:
    description: "Allows the user to run the Cristelia command"
    default: true